# Generated by Django 4.2.29 on 2026-03-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeckArchetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("format", models.CharField(max_length=50)),
                ("colors", models.CharField(max_length=10)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "deck_archetypes",
            },
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user_logins",
            },
        ),
        migrations.CreateModel(
            name="UserDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decklist", models.TextField(blank=True, null=True)),
                ("decklist_link", models.TextField(blank=True, null=True)),
                ("num_matches", models.IntegerField(default=0)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_decks",
                        to="mtg_profiles.deckarchetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to="mtg_profiles.userlogin",
                    ),
                ),
            ],
            options={
                "db_table": "user_decks",
            },
        ),
        migrations.CreateModel(
            name="PlayerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play", models.BooleanField()),
                ("match_result", models.CharField(max_length=10)),
                ("g1_result", models.CharField(max_length=10)),
                ("g2_result", models.CharField(blank=True, max_length=10, null=True)),
                ("g3_result", models.CharField(blank=True, max_length=10)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="matches",
                        to="mtg_profiles.deckarchetype",
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="mtg_profiles.userdeck",
                    ),
                ),
                (
                    "opp_archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="opponent_matches",
                        to="mtg_profiles.deckarchetype",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opponent_matches",
                        to="mtg_profiles.userlogin",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="mtg_profiles.userlogin",
                    ),
                ),
            ],
            options={
                "db_table": "match_results",
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opponent_deck", models.CharField(blank=True, max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("draw", "Draw")],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="mtg_profiles.deck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_sideboard", models.BooleanField(default=False)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="mtg_profiles.deck",
                    ),
                ),
            ],
        ),
    ]
