# Generated by Django 4.2.29 on 2026-03-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("field_value", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_fields",
                        to="mtg_profiles.userlogin",
                    ),
                ),
            ],
            options={
                "db_table": "profile_fields",
            },
        ),
    ]
