# Generated by Django 4.2.29 on 2026-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0005_userdeck_last_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogin",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
