# Generated by Django 4.2.29 on 2026-04-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0006_userlogin_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilefield",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("x", "X"),
                    ("moxfield", "Moxfield"),
                    ("mtgeloproject", "MTG Elo Project"),
                    ("discord", "Discord"),
                    ("twitch", "Twitch"),
                    ("arena", "Arena Username"),
                    ("mtgo", "MTGO Username"),
                ],
                max_length=50,
            ),
        ),
    ]
