# Generated by Django 4.2.29 on 2026-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0007_alter_profilefield_field_name_add_arena_mtgo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "formats",
            },
        ),
    ]
