# Generated by Django 4.2.29 on 2026-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0008_add_format_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deckarchetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="deckarchetype",
            unique_together={("name", "format", "colors")},
        ),
    ]
