# Generated by Django 4.2.29 on 2026-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0009_alter_deckarchetype_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdeck",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
