# Generated by Django 4.2.29 on 2026-04-29 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0010_add_userdeck_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdeck",
            name="last_played",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
