# Generated by Django 4.2.29 on 2026-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0011_alter_userdeck_last_played_remove_auto_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdeck",
            name="last_played",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
