# Generated by Django 4.2.29 on 2026-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_profiles", "0012_alter_userdeck_last_played_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedBetaEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "approved_beta_emails",
            },
        ),
    ]
